### ISSUE TITLE
Class SyntaxError

### ISSUE THREAD

**Issue by imperez** [vdemedes/mailman#1]
I'm currently trying to use the newest version with ES6 classes but when I require the module I get the below error. I'm running Node 0.11.14 with the harmony flag. I've been looking for some solutions but keep coming up empty.

Did you run into this issue before?

    class Mailman {
    ^^^^^
    SyntaxError: Unexpected reserved word
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Object.loader (/Users/rich/Sites/muraco/node_modules/mailman/node_modules/6to5/lib/6to5/register.js:84:16)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/rich/Sites/muraco/node_modules/mailman/index.js:5:18)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

**Comment by vdemedes** [comment]
Fix is in progress, thanks for letting me know.

**Comment by vdemedes** [comment]
There is a mailman@0.3.2 on npm, which fixes the issue. Thank you!
